version: '3.1'

services:

  task-management-system-service:
    build: ./taskService
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.datasource.url=jdbc:postgresql://localhost:5432/Task-Management-System
      - spring.datasource.username=postgres
      - spring.datasource.password=admin
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring.jpa.properties.hibernate.show_sql=true
      - spring.jpa.hibernate.ddl-auto = update
      - spring.mvc.hiddenmethod.filter.enabled=true


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 5432:5432