version: '3.1'

services:

  task-management-system-service:
    build: ./taskService
    ports:
      - 8080:80

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Task-Management-System

  adminer:
    image: adminer
    restart: always
    ports:
      - 5432:5432